# Generated by Django 5.1.1 on 2024-10-01 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Prodcut",
            new_name="Product",
        ),
    ]
